# Generated by Django 4.2.10 on 2026-03-27 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('headline', models.CharField(max_length=160)),
                ('intro', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('resume_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('summary', models.TextField()),
                ('tech_stack', models.CharField(max_length=255)),
                ('live_url', models.URLField(blank=True)),
                ('source_url', models.URLField(blank=True)),
                ('featured', models.BooleanField(default=True)),
                ('created_at', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-featured', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('level', models.PositiveSmallIntegerField(default=80)),
            ],
            options={
                'ordering': ['-level', 'name'],
            },
        ),
    ]
