# Generated by Django 6.0.3 on 2026-04-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_aboutsection_achievement_certification_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UGCNetPYQ",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "paper",
                    models.CharField(
                        choices=[
                            ("paper-1", "Paper 1"),
                            ("paper-2", "Paper 2 (Computer Science and Applications)"),
                        ],
                        default="paper-1",
                        max_length=12,
                    ),
                ),
                ("subject", models.CharField(max_length=120)),
                ("year", models.PositiveSmallIntegerField(default=2026)),
                ("question_text", models.TextField()),
                ("option_a", models.CharField(max_length=255)),
                ("option_b", models.CharField(max_length=255)),
                ("option_c", models.CharField(max_length=255)),
                ("option_d", models.CharField(max_length=255)),
                (
                    "correct_option",
                    models.CharField(
                        choices=[
                            ("A", "Option A"),
                            ("B", "Option B"),
                            ("C", "Option C"),
                            ("D", "Option D"),
                        ],
                        max_length=1,
                    ),
                ),
                ("solution", models.TextField(help_text="Short solution or approach")),
                ("explanation", models.TextField(help_text="Detailed explanation")),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=1)),
            ],
            options={
                "verbose_name": "UGC NET PYQ",
                "verbose_name_plural": "UGC NET PYQs",
                "ordering": ["paper", "subject", "-year", "order", "id"],
            },
        ),
    ]
