# Generated by Django 6.0.3 on 2026-04-09 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_ugcnetpyq"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UGCNetPYQ",
        ),
    ]
